---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    pull: default
    image: rancher/dapper:v0.4.1
    commands:
      - dapper ci
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: github-binary-publish-release
    pull: default
    image: plugins/github-release
    settings:
      checksum:
        - sha256
      files:
        - "bin/kontainer-engine-driver-karbon-*"
      api_key:
        from_secret: github_token
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag
      ref:
        exclude:
          - "refs/tags/*rc*"

  - name: github-binary-publish-prerelease
    pull: default
    image: plugins/github-release
    settings:
      checksum:
        - sha256
      files:
        - "bin/kontainer-engine-driver-karbon-*"
      prerelease: true
      api_key:
        from_secret: github_token
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag
      ref:
        - refs/head/master
        - "refs/tags/*rc*"

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
